services:

  routes-reservations-service:
    build: .

    expose:
      - "4000"

    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/routesdb
      - JWT_SECRET=supersecretkey

    depends_on:
      - mongo

    networks:
      - internal-services
      - data-network

  mongo:
    image: mongo

    volumes:
      - mongo-data:/data/db

    networks:
      - data-network

volumes:
  mongo-data:

networks:
  internal-services:
    external: true

  data-network:
    external: true